# deploy-roles.yml
---
- name: Install all required Ansible roles
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Create roles directory
      file:
        path: "{{ playbook_dir }}/roles"
        state: directory

    - name: Install roles from requirements.yml (with error handling)
      ansible.builtin.command:
        cmd: ansible-galaxy install -r requirements.yml -p roles/ --force --ignore-errors
      register: install_result
      changed_when: install_result.rc == 0

    - name: Check if roles were installed
      stat:
        path: "{{ playbook_dir }}/roles/{{ item }}"
      loop:
        - lighthouse
        - vector
        - clickhouse
      register: roles_check

    - name: Display installation status
      debug:
        msg: "{{ item.stat.exists | ternary(item.item + ': ✓ Installed', item.item + ': ✗ Missing') }}"
      loop: "{{ roles_check.results }}"
