---
- src: https://github.com/AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: "master"
 # version: "1.13"
  name: clickhouse

- src: https://github.com/sapr797/ansible-role-vector.git
  scm: git
  version: "v1.0.0"
  name: vector

- src: https://github.com/sapr797/ansible-role-lighthouse.git
  scm: git
  version: "v1.0.1"
  name: lighthouse
