---
# Ansible Galaxy requirements for Lighthouse Monitoring System

# 1. ClickHouse role (included locally)
- src: ./roles/clickhouse
  name: clickhouse

# 2. Your custom roles (referencing GitHub repositories)
- src: https://github.com/sapr797/ansible-role-lighthouse.git
  scm: git
  version: "main"
  name: lighthouse

- src: https://github.com/sapr797/ansible-role-vector.git
  scm: git
  version: "main"
  name: vector

# Alternative if roles are included locally:
# - src: ./roles/lighthouse
#   name: lighthouse
# - src: ./roles/vector
#   name: vector
